- fixed cyrillic layout issue
deskflow/deskflow pull request #6890
Opened 2020-12-28 11:09 UTC by bellerofonte

this PR is for #6862 

I've investigated the issue and came to following results (_macOS runs Synergy server, Linux runs synergy client_):

1. If macOS's keyboard layout is EN(US), **any** layout on Linux works pretty well
2. If macOS's keyboard layout is RU(RU) and Linux **hasn't** RU layout added - **nothing** gets typed
3. If macOS's keyboard layout is RU(RU) and Linux **hasn't** RU layout added - Cyrillic characters get **always** typed **whatever** layout is chosen on Linux.

So I decide to remap every incoming `KeyID` on client side using hardcoded table. I.e. I tried to translate any incoming `Cyrillic unicode key id` into `Basic Latin unicode key id` using may Macbook's _[physical]_ keyboard layout.
This still works not ideal, but **much** more comfortable to use.

2020-12-29 06:32 UTC, ignacionr commented
Здравствуйте @bellerofonte  !

First let me say thank you for actively sharing your take on Synergy, this encourages us a great deal.
Secondly, let me empathise with you as a daily user of both EN and RU mappings.

Finally, even though we will surely take into account this approach, I guess you understand it and it may not even need said but the PR cannot be merged as is, and would need a lot of work to get to a point where it can reach our vast user base (re-mapping would need to be an opt-in or auto-assessed element, it would need to cope not only with other languages but even within Russian, it would require the standard, the PC, and the АБВ layouts).

Please remain in contact, and do consider we are hiring.

2020-12-29 07:09 UTC, bellerofonte commented
Hi @ignacionr!

Thank you for your response. 
> I guess you understand it and it may not even need said but the PR cannot be merged as is
Sure, I just wanted you to note this approach. I'm closing this PR, but I will continue to improve this branch for my personal environment. You are welcome to use my work as soon as you need it.

2024-09-12 10:04 UTC, nbolton commented
Hi @bellerofonte, just noticed this PR was closed without the work being used. I'm reopening this in the hope that we can perhaps use your contribution.

2024-12-18 15:34 UTC, sithlord48 commented
This should be rechecked to see if its still a vaild issue now that we should have proper utf16 pairs.

2025-03-26 09:23 UTC, nbolton requested changes
Are you able to fix these merge conflicts?

2025-03-26 09:23 UTC, nbolton commented on src/lib/synergy/KeyState.h
> +    */
Commented out code needs removing.

2025-04-22 09:57 UTC, nbolton commented
> Are you able to fix these merge conflicts?

Unfortunately, seems like another PR we don't have bandwidth to fix :disappointed:

2025-04-22 09:57 UTC, closed without merging