Added active screen filename output to enable app integrations with things like key mappers
deskflow/deskflow pull request #7217
Opened 2022-08-31 23:08 UTC by jglanz

Added active screen filename output to enable app integrations with things like key mappers

- defaults to `~/.synergy-active-screen`
- Preferences panel option with browse button
- Added command line option `--active-screen-filename` to `synergys` too
- And added support to read from conf file in `options` section named `activeScreenFilename`

I personally use it with `kinto` on top of `xkeysnail` and it is MAGIC

If it's ok to merge then I'll happily clean it up (super busy at work, so it may take a minute), but regardless, hope this helps others.

J

2022-10-12 08:25 UTC, SerhiiGadzhilov requested changes
Thank you for the PR but it’s not ok to merge due to the following reasons:
1. This PR introduces QT dependencies for synergys.
2. This PR introduces C++17 dependencies which can’t be used due to some OSs which we still support.
3. Unresolved conflicts
4. Configuration files like “.gdbinit” and “.lldbinit” should be excluded from the PR.

2022-10-12 08:25 UTC, SerhiiGadzhilov commented on CMakeLists.txt
> +set (CMAKE_CXX_EXTENSIONS ON)
We can’t simply switch to C++17 because some OSs that we have to support don’t support this standard.

2022-10-12 08:25 UTC, SerhiiGadzhilov commented on src/cmd/synergys/CMakeLists.txt
> +find_package(Qt5 COMPONENTS Core Widgets Network LinguistTools)
synergys shouldn't have QT dependency

2022-10-12 08:25 UTC, SerhiiGadzhilov commented on src/cmd/synergys/synergys.cpp
> +#include <QThread>
synergys shouldn't have QT dependency

2022-10-12 08:25 UTC, SerhiiGadzhilov commented on src/lib/server/CMakeLists.txt
> +set(CMAKE_INCLUDE_CURRENT_DIR ON)
This project shouldn't have QT dependency

2023-07-27 09:44 UTC, nbolton commented
Closing since no reply, please re-open when changes are made.

2024-09-12 09:52 UTC, nbolton commented
Actually, I think this could be useful, so I'll pick this up.

2025-03-14 14:54 UTC, nbolton commented
Unfortunately, as this is very far behind master now nad we don't have the bandwidth to rebase master to this PR, I'm forced to close the PR. If there is any interest in porting this code to the latest master, I would welcome a new PR.

2025-03-14 14:54 UTC, closed without merging