ci: auto format and commit amend then rebase
deskflow/deskflow pull request #7530
Opened 2024-09-18 22:09 UTC by nbolton

2024-09-18 22:56 UTC, sithlord48 requested changes

2024-09-18 22:56 UTC, sithlord48 commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
Please remove this unneeded change

2024-09-18 23:03 UTC, nbolton commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
This is to trigger the linter. I'll let you know when the PR is out of draft for you to review.

2024-09-18 23:04 UTC, sithlord48 commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
Looks like its not pushing back to the repo

2024-09-18 23:14 UTC, nbolton commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
Oh I've been having fun with that one! 

It does, but I keep pushing up the lint error to re-trigger it.

See #7529 and #7528 for my previous mistakes; turns out if you --amend to fetch depth 1, it pushes changes to all files. I figured out the solution is to add:
```
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 2
```
to
```
      - name: Checkout
        uses: actions/checkout@v4
```

2024-09-18 23:16 UTC, sithlord48 commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
why not depth of 0 ?

2024-09-18 23:19 UTC, nbolton commented on CMakeLists.txt
> +  cmake_minimum_required(VERSION 3.5)
I don't think that depth is needed; `0` brings in all the tags which I don't need here. Depth of `2` works well.

The problem I have now is that GitHub workflows can't be triggered by GitHub (e.g. if GitHub does `git push`), so once the linter makes it's fixes, the workflow doesn't re-run and gets stuck... not quite sure where to go from here. I'll sleep on it.

![image](https://github.com/user-attachments/assets/b2a22a8d-3233-4e8b-85ec-7a2ffdec6201)

2024-09-20 13:19 UTC, sithlord48 commented
Moved to discussion https://github.com/deskflow/deskflow/discussions/7536

2024-09-20 13:19 UTC, closed without merging