feat: use new Deskflow graphics
deskflow/deskflow pull request #7551
Opened 2024-09-21 17:21 UTC by nbolton

2024-09-21 19:59 UTC, sithlord48 requested changes

2024-09-21 19:59 UTC, sithlord48 commented on res/deskflow.svg
can we get the svg larger then 20x20

2024-09-21 21:33 UTC, nbolton commented on res/deskflow.svg
Sure, what size do you want it?

2024-09-21 22:10 UTC, nbolton commented on res/deskflow.svg
I went with 400x400, I think that's big enough.

2024-09-22 11:09 UTC, sithlord48 approved these changes

2024-09-22 11:09 UTC, merged