ci: relocate commercial code downstream
deskflow/deskflow pull request #7579
Opened 2024-09-23 16:51 UTC by nbolton

2024-09-23 17:56 UTC, sithlord48 reviewed
You should always use `CMAKE_SOURCE_DIR` , `CMAKE_BINARY_DIR` or `CMAKE_CURRENT_BINARY_DIR` or `CMAKE_CURRENT_BINARY_DIR` to find these paths. for what reason do you feel like you need to change them?

2024-09-26 15:25 UTC, sithlord48 commented on res/dist/flatpak/deskflow.yml
> +app-id: org.deskflow.Deskflow
This is incorrect, the id should be `io.github.deskflow.Deskflow`.

2024-09-26 15:40 UTC, nbolton commented on res/dist/flatpak/deskflow.yml
> +app-id: org.deskflow.Deskflow
Please help me to understand why.

2024-09-26 15:43 UTC, nbolton commented on res/dist/flatpak/deskflow.yml
>  runtime-version: "5.15-21.08"
Thanks, I was planning on fixing Flatpack in a separate PR. I'm going to leave this for now.

2024-09-26 15:48 UTC, nbolton commented on res/dist/flatpak/deskflow.yml
>  runtime-version: "5.15-21.08"
https://github.com/deskflow/deskflow/issues/7593

2024-09-27 18:46 UTC, nbolton commented on res/dist/flatpak/deskflow.yml
> +app-id: org.deskflow.Deskflow
Almost ready to submit PR for review, so let me know about this if you have time. If not we can discuss in another PR.

2024-09-30 13:07 UTC, sithlord48 commented
Converted to a draft until your ready here

2024-09-30 15:31 UTC, sithlord48 commented on CMakePresets.json
> -      "name": "macos",
Why change this from macos ? I would think that would be pretty common

2024-09-30 15:47 UTC, sithlord48 requested changes
I got a few things then i stopped reviewing the rest. Most of the things i think we can fix in additional prs (at least the bit i did look at) but i am not sure about the naming changes using cmake vars being helpful or just more vars i need to set .

2024-09-30 15:47 UTC, sithlord48 commented on CMakePresets.json
>        "generator": "Unix Makefiles"
On mac os you may want to use the [XCode](https://cmake.org/cmake/help/latest/generator/Xcode.html)  generator

2024-09-30 15:47 UTC, sithlord48 commented on Doxyfile
> +PROJECT_LOGO           = res/app.svg
I am not sure i am a fan of the general binary names.

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Build.cmake
> +  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin")
This is generally not needed when your using cmake it will take care of the various parts finding one anther for you. This is also not making deployment any easier or harder.

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Build.cmake
> +    set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0")
Qt6 needs at least   `11`

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Build.cmake
> +                 ${PROJECT_BINARY_DIR}/config/gui_config.h)
Perhaps prefix the source with `${PROJECT_SOURCE_DIR}` ? .

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Build.cmake
> +      ${GUI_BINARY_NAME}
Not sure how i feel about this.

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Definitions.cmake
>    if(NOT "$ENV{GIT_SHA}" STREQUAL "")
Why is this an Environmental Variable ? 

What if i didn't get the code via git ?

2024-09-30 15:47 UTC, sithlord48 commented on cmake/Definitions.cmake
>      add_definitions(-DGIT_SHA_SHORT="${GIT_SHA_SHORT}")
consider using configure file to make a version header

2024-09-30 15:48 UTC, sithlord48 commented
Can you split the fix for #7443 ? (sorry)

2024-09-30 16:59 UTC, nbolton commented on CMakePresets.json
> -      "name": "macos",
I'm easy either way. When I originally wrote that code, `macos` felt weird but I ran with it and I've been meaning to try it with just "mac" to see if it's more readable. I figured that `mac` looked a bit better, but it was purely subjective. I can change it back if you like.

2024-09-30 17:01 UTC, nbolton commented
> Can you split the fix for #7443 ? (sorry)

I'll take a look :slightly_smiling_face:

2024-09-30 17:14 UTC, nbolton commented on Doxyfile
> +PROJECT_LOGO           = res/app.svg
Can you think of any disadvantages of this image name? Thinking about it from a contributors perspective.

2024-09-30 17:15 UTC, nbolton commented on cmake/Build.cmake
> +  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin")
Hmm, I can't remember why I did this but I seem to remember it being important for some reason. Happy to look at taking this out in a different PR?

2024-09-30 17:17 UTC, nbolton commented on cmake/Build.cmake
> +    set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0")
I believe we have to set it to 12 because of C++20, but I can't remember exactly. Again, this isn't really related to this PR, just moving code around. Ok to look at it in a separate PR?

2024-09-30 17:17 UTC, nbolton commented on cmake/Build.cmake
> +                 ${PROJECT_BINARY_DIR}/config/gui_config.h)
Good catch. Will take a look.

2024-09-30 17:18 UTC, nbolton commented on cmake/Build.cmake
> +      ${GUI_BINARY_NAME}
Me too, but I can't think of a better way to fix the problem now. This feels like part of a much bigger problem that we need to solve separately.

2024-09-30 17:20 UTC, nbolton commented
> I got a few things then i stopped reviewing the rest. Most of the things i think we can fix in additional prs (at least the bit i did look at) but i am not sure about the naming changes using cmake vars being helpful or just more vars i need to set . 

Sounds good. I think we can iterate on this in other PRs. Nothing is set in stone and getting this done is probably more important than getting it perfect.

2024-09-30 19:30 UTC, nbolton commented on .github/workflows/ci.yml
> +  PACKAGE_RETENTION_DAYS: 3
I like to follow the DRY (don't repeat yourself) principle. So if there's something repeated several times, I prefer to set it as a constant. Env vars aren't awesome for consts, but I don't believe there is another way in GitHub workflows.

2024-09-30 20:38 UTC, sithlord48 commented on cmake/Definitions.cmake
>      add_definitions(-DGIT_SHA_SHORT="${GIT_SHA_SHORT}")
i will likey want to use what i do else where for versions so i may do this in time as well.

2024-09-30 20:40 UTC, sithlord48 commented on cmake/Build.cmake
> +    set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0")
Ah yes idk about c++20 's version im ok with using 12 in that case.

2024-09-30 20:42 UTC, sithlord48 commented on .github/workflows/ci.yml
> +  PACKAGE_RETENTION_DAYS: 3
Sorry what i meant was that there is almost no reason to set the retention time.

2024-09-30 20:43 UTC, sithlord48 commented on CMakePresets.json
> -      "name": "macos",
i feel like macos or some variant of it MacOS macOS what have you is the norm. so i would just have kept `macos`

2024-09-30 20:46 UTC, sithlord48 commented on CMakePresets.json
>        "generator": "Unix Makefiles"
ill have to see what the default is. I know we need to then open that in xcode it it will produce a project and build files that xcode (the native) toolchain will consume . you should then be able to use cmake --build to build it

2024-09-30 20:47 UTC, sithlord48 commented on Doxyfile
> +PROJECT_LOGO           = res/app.svg
well its the project logo so i think if i was forking and making a new one of my first things would be to replace this and using the project name.svg seams to make sense to me .. same idea w/ the binaries

2024-09-30 20:48 UTC, sithlord48 commented on cmake/Definitions.cmake
>    if(NOT "$ENV{GIT_SHA}" STREQUAL "")
just seams weird . can fix it later its not hurting anything

2024-10-01 06:37 UTC, nbolton commented on Doxyfile
> +PROJECT_LOGO           = res/app.svg
I was thinking about it this way: For downstream forks, it'd be easier if they didn't have to rename files, that way less would get out of sync. IMO, using the project name for any file is a bit vague and lazy. It seems to be the kind of thing a junior developer tends to do. How about we call it `logo.svg` instead? I'm a big fan of naming files after their purpose.

2024-10-01 07:14 UTC, nbolton commented
@sithlord48 Quick thought, maybe the commit prefix is `chore!:` and not `ci:` (perhaps not `feat!:`)

2024-10-01 08:04 UTC, nbolton commented
> Can you split the fix for #7443 ? (sorry)

Done 👍 #7595

2024-10-01 13:09 UTC, sithlord48 reviewed
Land it if you want I think the generic names are not needed but do you.

2024-10-01 13:24 UTC, nbolton commented
> Land it if you want I think the generic names are not needed but do you.

We can change them back if they don't have a positive effect.

2024-10-01 13:39 UTC, merged