Add PR review value to README.md
deskflow/deskflow pull request #7642
Opened 2024-10-12 11:47 UTC by nbolton

Proposed additional value:

> - All pull requests are reviewed and approved (apart from minor doc changes)

A project that lands PRs without review is a one-man show and putting a project leader above the law sets a bad example.

We believe decisions should be made collectively, and that applies to deciding what code to land in `master`. We already have required PR review/approval in our branch protection rules, of course, but this makes it clear to our community (especially to newcomers) where we stand on this.

I added one caveat to this value, which I'm happy to forgoe if it's undesireable: '(apart from minor doc changes)' 

By this, I mean things like minor typo fixes, broken link/image fixes, etc.

2024-10-12 11:50 UTC, nbolton commented
Just noticed the commit message, will fix.

2024-10-12 20:11 UTC, nbolton commented on README.md
> +- All pull requests are reviewed and approved (apart from minor doc changes)
Or maybe...
```
- All pull requests require review and approval (apart from minor doc changes)
```

2024-10-13 00:32 UTC, sithlord48 commented on README.md
> +- All pull requests are reviewed and approved (apart from minor doc changes)
Imho this while good to have does not belong in this document.
Really this kinda of info (about the dev /  review process) should go into the `CONTRIBUTING` file were we can point out what is expected of contributors.

2024-10-13 18:53 UTC, nbolton commented on README.md
> +- All pull requests are reviewed and approved (apart from minor doc changes)
Do you think the whole values section should go in `CONTRIBUTING` there or just this one line? Like you said, the README got rambly and we need to fix that.

2024-10-13 19:02 UTC, sithlord48 requested changes
lets do this more inline with #7665

2024-10-13 20:22 UTC, nbolton commented
> lets do this more inline with #7665

Cool, I'll close. Added a note to that issue.

2024-10-13 20:22 UTC, closed without merging