chore: add note about known wayland issues in bug_template
deskflow/deskflow pull request #7648
Opened 2024-10-12 14:22 UTC by sithlord48

In an attempt to slow the duplicate Wayland portal issues being raised. 

 - Add os option  for  Linux (X11) / Llinux (wayland)
 - Add note for linux(wayland ) bug reporters to check the known issues first.

2024-10-12 19:45 UTC, nbolton requested changes

2024-10-12 19:45 UTC, nbolton commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: textarea
Very minor, I find adding space between blocks improves readability.

```suggestion
      required: true

  - type: textarea
```

2024-10-12 19:45 UTC, nbolton commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: textarea
Would this be better as a checkbox? Something like...
```
  - type: checkboxes
    id: linux-wayland
    attributes:
      label: Wayland on Linux
      description: If you using Wayland on Linux, please review the [known issues](https://github.com/deskflow/deskflow/discussions/7499) before reporting.
      options:
        - label: I have reviewed the Wayland known issues and my issue is new
        - label: I am not using Wayland on Linux
```

2024-10-13 00:33 UTC, sithlord48 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: textarea
OH yeah that would for sure be better

2024-10-13 12:45 UTC, sithlord48 commented
Added a note here about mac is signing also

2024-10-13 18:01 UTC, merged