ci: single depends linux
deskflow/deskflow pull request #7771
Opened 2024-10-20 23:22 UTC by sithlord48

2024-10-21 15:09 UTC, nbolton commented
> Error: Process completed with exit code 100.

Looks like Fedora 40 is failing due to `dnf install` returning `100` which AFAIK means "Updates available." (kinda silly)

2024-10-21 15:12 UTC, nbolton commented
Heads up, the `Dockerfile` for each distro used by `.github/workflows/build-containers.yml` also references `./scripts/install_deps.py` which is how the containers have the correct packages pre-loaded (and are at most a week out of date).

2024-10-22 09:03 UTC, nbolton commented
> sithlord48 requested a review from nbolton 3 hours ago

I'm guessing you intended to switch this to open.

2024-10-22 09:19 UTC, nbolton approved these changes
Some optional suggestions you may want to implement, but your call. Spotted some nits, but will fix in new PR.

2024-10-22 09:19 UTC, nbolton commented on .github/actions/install-dependencies/action.yml
> +    # This mirrors instructions at https://apt.kitware.com
Is this comment still relevant?

2024-10-22 09:19 UTC, nbolton commented on .github/actions/install-dependencies/action.yml
> +    - name: Dependencies (vcpkg)
```suggestion
    - name: Build and cache vcpkg
```

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/build-containers.yml
We could rename our Debian runner to `debian-trixie-amd64` for accuracy but I'm happy either way.

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/ci.yml
> +            extra-cmake-config: "-G Ninja -DCMAKE_INSTALL_PREFIX"
I thought you wanted to ditch the arm runner.

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/ci.yml
> +        id: deploy
```suggestion
        id: dependencies
```

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/ci.yml
> +            ${{github.workspace}}/dist/deskflow[-_]*.*
I'm guessing the `dist` dir is eventually going away?

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/ci.yml
> +    if: (github.ref == 'refs/heads/master')
Oh, hang on a sec... our un-landed PR builds were being sent to release? Oops.

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/sonarcloud-analysis.yml
> +      - run: apt install curl unzip gcovr  -y
```suggestion
      - name: Install dependencies (extra)
        run: apt install curl unzip gcovr  -y
```

2024-10-22 09:19 UTC, nbolton commented on .github/workflows/valgrind-analysis.yml
> +      - run: apt install valgrind cmake -y
```suggestion
      - name: Install dependencies (extra)
        run: apt install valgrind cmake -y
```

2024-10-22 09:19 UTC, nbolton commented on meson.build
Makes me happy.

2024-10-22 09:19 UTC, nbolton commented on src/gui/src/MainWindow.cpp
> +#ifdef Q_OS_LINUX
Good change... this is defined on BSD-derived Unix-like too, right? (e.g. FreeBSD)

2024-10-22 09:19 UTC, nbolton commented on src/lib/platform/EiScreen.cpp
```suggestion
```

2024-10-22 13:06 UTC, sithlord48 commented on src/gui/src/MainWindow.cpp
> +#ifdef Q_OS_LINUX
Afaik bsd does not have wayland so this check is really still linux only

2024-10-22 13:19 UTC, sithlord48 commented on src/gui/src/MainWindow.cpp
> +#ifdef Q_OS_LINUX
We do not need this check if the var we check is empty we will say we are not on wayland .

2024-10-22 13:23 UTC, sithlord48 commented on src/lib/platform/EiScreen.cpp
part of #7781

2024-10-22 13:23 UTC, sithlord48 commented on src/gui/src/MainWindow.cpp
> +#ifdef Q_OS_LINUX
On #7781

2024-10-22 13:24 UTC, sithlord48 commented on .github/workflows/ci.yml
> +            extra-cmake-config: "-G Ninja -DCMAKE_INSTALL_PREFIX"
Well the other method of using qemu will take about 40 minutes to build each .
I figured we can lookin to this in another pr.

For now i would like to leave them as is

2024-10-22 13:38 UTC, sithlord48 commented on .github/workflows/build-containers.yml
Id rather use the numeric release because to people that don't follow debian we all know 13 > 12 but not all of us know if trixie , bookwork , or buster is the current codename.

2024-10-22 13:41 UTC, sithlord48 commented on .github/workflows/ci.yml
> +            ${{github.workspace}}/dist/deskflow[-_]*.*
well when cmake makes the packages they are produced in the root of the build dir so that is where we are gonna look for them. 

The `dist` is temp until i have the mac and windows packages being produced property via cpack

2024-10-22 13:42 UTC, sithlord48 commented on .github/workflows/ci.yml
> +    if: (github.ref == 'refs/heads/master')
No they are not but the step starting and spending time to dl the artifacts that we dont release. This just makes it so that does not happen

2024-10-22 13:50 UTC, nbolton commented on .github/workflows/build-containers.yml
Ok sounds good, that's why I used the number in the first place so it sounds like we both have the same point of view on this one. Debian wants us to use "Trixie" because they're not officially calling it 13 yet, but we all know that's what's going to happen.

2024-10-22 13:56 UTC, nbolton commented on .github/workflows/ci.yml
> +            extra-cmake-config: "-G Ninja -DCMAKE_INSTALL_PREFIX"
Cool... to be honest GitHub charges next to nothing for their ARM runners, so it's no big deal to stick with paid runners. Problem is in this PR, that CI will now fail for downstream forks (contributors) when they enable workflows in their fork. IIRC, the workflow will just hang there forever waiting for the ARM runner to come online (which it never will unless they have a paid runner with exactly the same name).

We may want to drop ARM for now in this PR (since we're no longer using the 'clever' JSON filter solution) and reintroduce it in a different PR (to fix #7785) as a new workflow or job that only runs if you have paid runners.

2024-10-22 14:40 UTC, sithlord48 commented on .github/workflows/ci.yml
> +            extra-cmake-config: "-G Ninja -DCMAKE_INSTALL_PREFIX"
Yes ill remove it for now and we can add it back later.

2024-10-22 15:34 UTC, nbolton requested changes
Just spotted an error in CI.
```
d1f1-1ed3-43c0-8e89-6b897e72bae9.sh: 2: -G: not found
```

2024-10-22 15:34 UTC, nbolton commented on .github/workflows/ci.yml
> +            ${{ steps.install-dependencies.outputs.vcpkg-cmake-config }}
Oops, didn't spot this on my last pass.

I don't think the PowerShell backtick linebreak approach works on `sh`/`bash`:
https://github.com/deskflow/deskflow/actions/runs/11462609763/job/31894430876?pr=7771
```
Run cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_COMPILE_WARNING_AS_ERROR=ON `
  cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_COMPILE_WARNING_AS_ERROR=ON `
    -G Ninja -DCMAKE_INSTALL_PREFIX `
    
  shell: sh -e {0}
  env:
    GIT_SHA: b9a86a074f903af10db460b44cce68dbe4[2](https://github.com/deskflow/deskflow/actions/runs/11462609763/job/31894430876?pr=7771#step:7:2)c0288
    PACKAGE_PREFIX: deskflow
    PACKAGE_PATH: ./dist
    CMAKE_CONFIGURE: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
/__w/_temp/901[3](https://github.com/deskflow/deskflow/actions/runs/11462609763/job/31894430876?pr=7771#step:7:3)d1f1-1ed3-43c0-8e89-6b897e72bae9.sh: 2: -G: not found
```

Maybe the best approach is to split this into two steps, "Configure (Unix)" and "Configure (Windows)":
```
     # Windows with backtick (`) linebreaks
      - name: Configure (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          ${{env.CMAKE_CONFIGURE}} `
            ${{ matrix.target.extra-cmake-config }} `
            ${{ steps.install-dependencies.outputs.vcpkg-cmake-config }}

     # Non-Windows with backslack (\) linebreaks
      - name: Configure (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          ${{env.CMAKE_CONFIGURE}} \
            ${{ matrix.target.extra-cmake-config }}
```

Or, if Windows will let you run CMake outside of PowerShell (not sure if possible), maybe we could have a single step and use bash backslashes:
```
      - name: Configure
        shell: bash
        run: |
          ${{env.CMAKE_CONFIGURE}} \
            ${{ matrix.target.extra-cmake-config }} \
            ${{ steps.install-dependencies.outputs.vcpkg-cmake-config }}
```

And if that's all too much trouble, just remove the backticks and have it on one line:
```
      - name: Configure
        run: |
          ${{env.CMAKE_CONFIGURE}} ${{ matrix.target.extra-cmake-config }} ${{ steps.install-dependencies.outputs.vcpkg-cmake-config }}
```

IDK though, feels a bit dupey. Fucking PowerShell, eh? Why couldn't they adopt backslashes... oh yeah, it's a dir separator! :roll_eyes:

2024-10-22 15:34 UTC, nbolton commented on .github/workflows/ci.yml
>              extra-cmake-config: "-DCMAKE_OSX_ARCHITECTURES=\"arm64\" -DMACOSX_DEPLOYMENT_TARGET=12"
I wonder if it'd make things a bit readable if we called it `cmake-args` instead of `extra-cmake-config`?

2024-10-22 16:28 UTC, nbolton approved these changes

2024-10-22 16:29 UTC, merged