docs: readme add mac os xattr note
deskflow/deskflow pull request #7821
Opened 2024-10-28 11:57 UTC by sithlord48

add a tip for mac users to run xattr -c on the app post download
[Preview](https://github.com/deskflow/deskflow/blob/readme-update-2/README.md)

2024-10-28 11:59 UTC, nbolton requested changes
I found that that adding permission to the `deskflow` process (the GUI process) is sufficient. The only entry that shows by default is the `Deskflow` app bundle entry (capital 'D') but you have to manually add the `deskflow` GUI process (lower 'D).

2024-10-28 11:59 UTC, nbolton commented on README.md
> +> Mac os users may need to run `xattr -c /Applications/Deskflow.app` After copying the app too applicatons, You will also have to allow accessibility access to both the deskflow gui and the server /
```suggestion
> macOS users may need to run `xattr -c /Applications/Deskflow.app` after copying the app to `Applications`.
> You will also have to allow accessibility access to both the `Deskflow` app and the `deskflow` process.
```

2024-10-28 12:22 UTC, nbolton approved these changes

2024-10-28 12:22 UTC, merged

2024-10-29 02:06 UTC, DominikDeak commented
cheers for adding the tip