Clean up defines
deskflow/deskflow pull request #7824
Opened 2024-10-28 19:31 UTC by sithlord48

Trying to simplify the cmake and get ready to have all the packages in 
 - Remove DESKFLOW_APP_ID define
 -

2024-10-31 13:37 UTC, nbolton requested changes

2024-10-31 13:37 UTC, nbolton commented on res/win/version.rc.in
> +#define VER_PRODUCTNAME_STR         "@Deskflow@\0"
```suggestion
#define VER_PRODUCTNAME_STR         "Deskflow\0"
```

2024-10-31 13:37 UTC, nbolton commented on src/lib/gui/OSXHelpers.mm
Seems that the code style change is being applied here. Perhaps that should be a separate commit or a different PR?

2024-10-31 13:55 UTC, sithlord48 commented on src/lib/gui/OSXHelpers.mm
its because of the linter hook can't really do much about that if we force linting

2024-10-31 14:00 UTC, sithlord48 commented on res/win/version.rc.in
> +#define VER_PRODUCTNAME_STR         "@Deskflow@\0"
Good catch

2024-11-01 11:38 UTC, nbolton commented on src/lib/gui/OSXHelpers.mm
But you could make a new PR, right? I'm not sure I understand what's preventing a new PR.

2024-11-01 11:49 UTC, nbolton requested changes

2024-11-01 11:49 UTC, nbolton commented on src/lib/gui/config/AppConfig.cpp
> +const char AppConfig::m_ConfigFilename[] = "deskflow.conf";
This seems like duplication to me and a backwards step for maintainability and readability. Having magic strings repeated all over makes my eyes itch. IIRC, originally this was done out of laziness and I'd hate to repeat past mistakes.

I'm happy to do this later as a separate PR, but in terms of development best practice, I think we need to agree that repeating the same magic string all over the show is an anti-pattern.

Perhaps this'd be better as a function. I'd like to see only 2 constants:
```
const auto kCoreServerName = "deskflow-server";
const auto kCoreClientName = "deskflow-client";
```

The rest (`.exe`, `.sgc`, `.conf`) should be decoration added with a function.

2024-11-01 11:52 UTC, nbolton requested changes
Heads up, there are some issues to solve:
1. [Failing unit tests](https://github.com/deskflow/deskflow/actions/runs/11618409490/attempts/1#summary-32356114527)
1. [Intentionality issues](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&pullRequest=7824&id=deskflow_deskflow)

2024-11-01 12:49 UTC, sithlord48 commented on src/lib/gui/OSXHelpers.mm
Let me see if i can "fix" this maybe this is the `.editor-config`  i did have edit the mm file in kate as i was no on mac os making the changes so i didn't see the file in the ide

2024-11-13 01:13 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.cpp
> +const char AppConfig::m_ConfigFilename[] = "deskflow.conf";
done

2024-11-14 10:47 UTC, nbolton requested changes

2024-11-14 10:47 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
This level of abstraction is unnecessary and decreases readability.

2024-11-14 10:47 UTC, nbolton commented on src/lib/gui/config/AppConfig.cpp
> +  return s_2argTemplate.arg(s_CoreServerName, s_exeExt);
This is more readable.
```suggestion
  return QStringLiteral("%1.exe").arg(s_CoreServerName);
```

2024-11-14 10:47 UTC, nbolton commented on src/lib/gui/config/AppConfig.cpp
> +  return s_2argTemplate.arg(s_CoreClientName, s_exeExt);
This is more readable.
```suggestion
  return QStringLiteral("%1.exe").arg(s_CoreClientName);
```

2024-11-14 12:35 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
The string is used twice so i made a static var for it . that is the way .

2024-11-14 12:41 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
Its not about anyone knowing what the string is but only having to make at runtime a single copy. And makes maintenance easier as we have a single point for the string.

2024-11-14 13:36 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
I've seen this play out both ways over the years. Early on in my career, I would have encapsulated `.exe` into a constant without a second thought. But with more experience, I've realized how even seasoned developers can get tripped up by over-encapsulation. Now, I lean toward allowing minor duplication of immutable well-known strings rather than pushing DRY principles too far and risking unnecessary complexity.

2024-11-14 13:39 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
> Ia am simply not repeating myself in the code

Also, it’s worth mentioning—there's some inconsistency here in your narritive. By removing all the string encapsulation of "Deskflow" that I’d carefully put in place, your PR ends up repeating many strings multiple times. Repeating `.exe` is minor compared to that.

2024-11-14 13:45 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
I plan to address those in time.. i have a lot of spaghetti  to untangle to get to that point.

2024-11-14 13:50 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_exeExt = QStringLiteral(".exe");
To be clear, I am vehemently against `s_2argTemplate`. I think that's a preposterous level of encapsulation. I am also against `s_exeExt` but I can see how it is tempting. Experience tells me it's not a good idea.

2024-11-14 13:58 UTC, nbolton requested changes
Please remove `s_2argTemplate`.

2024-11-14 13:58 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_2argTemplate = QStringLiteral("%1%2");
```suggestion
```

2024-11-14 13:58 UTC, nbolton commented on src/lib/gui/config/AppConfig.cpp
> +  return s_2argTemplate.arg(s_CoreServerName, QStringLiteral(".exe"));
```suggestion
  return QStringLiteral("%1.exe").arg(s_CoreServerName);
```

2024-11-14 13:58 UTC, nbolton commented on src/lib/gui/config/AppConfig.cpp
> +  return s_2argTemplate.arg(s_CoreClientName, QStringLiteral(".exe"));
```suggestion
  return QStringLiteral("%1.exe").arg(s_CoreClientName);
```

2024-11-14 14:04 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_2argTemplate = QStringLiteral("%1%2");
Same as before, early on in my career, I would have encapsulated `"%1%2"` into a constant without a second thought. But with more experience, I now know how this level of overzealous encapsulation can impede others.

Re-surfacing my previous comment in the context of `"%1%2"` which is the same issue: 

> Generally speaking, here’s why bad encapsulation can be more problematic than minor string duplication:
> - Maintenance complexity: Bad encapsulation can lead to code that's harder to follow and extend. It creates tangled dependencies, where changing one part can unintentionally impact others, leading to more maintenance headaches.
> - Readability and usability: Poorly encapsulated code often hides logic in ways that aren’t clean or modular. Small duplications of a static, unchanging string, on the other hand, tend to keep things simple and readable.
> - Future modifications: Although duplication might seem worse, if the string truly doesn’t change, duplication here is a low-risk trade-off. Bad encapsulation, however, can introduce ripple effects, complicating future updates.
>
> In short, while duplication can feel like a compromise, bad encapsulation generally has a greater impact on maintainability and stability.

2024-11-14 14:06 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_2argTemplate = QStringLiteral("%1%2");
Id rather make one copy of  a QStringLiteral so we don't make the Exe larger for no reason

2024-11-14 14:08 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_2argTemplate = QStringLiteral("%1%2");
This is unnecessary optimization at the cost of readability.

2024-11-14 14:13 UTC, sithlord48 commented on src/lib/gui/config/AppConfig.h
> +  inline static const auto s_2argTemplate = QStringLiteral("%1%2");
No its correctly using QStrings and statics the way they are meant to be used for non user facing literals

2024-11-15 12:19 UTC, nbolton approved these changes
LGTM

2024-11-15 12:20 UTC, merged