Better names
deskflow/deskflow pull request #7845
Opened 2024-11-01 15:15 UTC by sithlord48

- Use `continuous` for the version portion of package names when not a tagged release

Todo: 
 Only works for cpack packages now

2024-11-01 17:30 UTC, marlop352 commented
- Not sure the continuous name is good since there would be no way to know if there was an update by the tag or filename(thinking about scripting/automations), there may be ways around that but since packagers shouldn't be using those, as far as I understood, then if deskflow itself can notify the user that there is an update it should be fine.

- The extra ".0" should be irrelevant if I understood you versioning scheme correctly as all tagged versions would end in ".0".

- **Do not** rename or mess around with the artifacts already released for 1.17.0.

Regarding the Windows questions:

1. windows or win ?
    - Either should work fine.
2. win$arch or win_$arch
    - Either should work fine but it's easier to read with the "_".
3. How do you all prefer the arm one be labeled ?
    - arm64
4. MSI being windows only do we need to include windows or just the arch ? (i.e deskflow-v_x64.msi)
    - From a user's(specially one that is less technical) point of view it's easier to find the right file if it has win or windows in the file name

Not a mac user so not gonna give an opinion about the mac questions.

2024-11-01 17:41 UTC, cdwmhcc commented
Will 1.19.0 and 1.19.0.3 coexist in the future? If they exist at the same time, then 1.19.0.3 > 1.19.0 or 1.19.0.3 < 1.19.0?

Several common combinations of macOS architectures:

- x86_64/aarch64
- x86_64/arm64
- x64/arm64
- intel/apple silicon

Recommended: x86_64/arm64

A complete example:
deskflow-1.17.0.0_macos_x86_64.dmg
deskflow-1.17.0.0_macos_arm64.dmg

2024-11-01 19:37 UTC, sithlord48 commented
> Will 1.19.0 and 1.19.0.3 coexist in the future? If they exist at the same time, then 1.19.0.3 > 1.19.0 or 1.19.0.3 < 1.19.0?
> 

They can. Within deskflow and within the packages the full 4 part version is always used.  
If your package manager / format does a version check for your example it would conclude that  `1.19.0.0` < `1.19.0.3 `.


> * Not sure the continuous name is good since there would be no way to know if there was an update by the tag or filename(thinking about scripting/automations), there may be ways around that but since packagers shouldn't be using those, as far as I understood, then if deskflow itself can notify the user that there is an update it should be fine.

The packages use the real 4 part version internally. The continuous name is only used so that `https://github.com/deskflow/deskflow/releases/download/continuous/deskflow-continuous_win64.msi` can be used as a perma link  to the 
last build from from master branch. 

All of the packages we make here are version aware so they should do the correct thing based on the internal versions 

You are correct in that the filename alone will not tell you if its newer then the last continuous you had downloaded. A simple solutions for such script could be to check the commit SHA, or release time vs the version last installed.  The oldest continuous release is our current one. A new one is always an upgrade. 


> * The extra ".0" should be irrelevant if I understood you versioning scheme correctly as all tagged versions would end in ".0".

 Future tagged versions will not have the Tweak Value of `0` in the name any longer  for example v 1.18.0  will have a name of `deskflow-1.18.0_win64.msi` (added example to the pr description)

2024-11-05 13:42 UTC, nbolton commented on .github/actions/get-version/action.yml
> +        echo "DESKFLOW_SEM_VERSION=$(git describe --long | sed 's/-/./g;s/v//g'  | grep -o '^[0-9]*.[0-9]*.[0-9]*.[0-9]*')">> $GITHUB_ENV
It seems that `DESKFLOW_SEM_VERSION` could contain a 4-digit version number, which is not SemVer (which can only have 3 dot-delimited digits followed by `-` and/or `+`). I think this may confuse people.

2024-11-05 13:52 UTC, nbolton commented
> A complete example:
> deskflow-1.17.0.0_macos_x86_64.dmg
> deskflow-1.17.0.0_macos_arm64.dmg

My preference is to use `kebab-case` (i.e. hyphen for delimiter) rather than mixing `-` and `_` for delimiters. That way, we can reserve underscore for use in things like `x86_64`.

Given that @sithlord48 is set on not using the 4th digit for stable releases, I'd be happy with:

- `deskflow-1.18.0-macos-x86_64.dmg`
- `deskflow-1.18.0-macos-arm64.dmg`
- `deskflow-1.18.0-windows-x64.msi`

2024-11-05 14:45 UTC, sithlord48 commented
you want - or _ I honestly don't care but i think name-version_OS just makes the OS part sick out a bit more.

2024-11-05 14:54 UTC, sithlord48 commented on .github/actions/get-version/action.yml
> +        echo "DESKFLOW_SEM_VERSION=$(git describe --long | sed 's/-/./g;s/v//g'  | grep -o '^[0-9]*.[0-9]*.[0-9]*.[0-9]*')">> $GITHUB_ENV
It is a SemVer as SemVer is M.m.P with `Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.` we use the label `.#`

2024-11-05 14:59 UTC, nbolton commented on .github/actions/get-version/action.yml
> +        echo "DESKFLOW_SEM_VERSION=$(git describe --long | sed 's/-/./g;s/v//g'  | grep -o '^[0-9]*.[0-9]*.[0-9]*.[0-9]*')">> $GITHUB_ENV
The key issue here is that while SemVer does allow labels for pre-release or build metadata, it explicitly specifies that these should be added after a hyphen or a plus sign, not as an extra numeric segment.

In SemVer:
- A pre-release version uses a hyphen: 1.0.0-alpha.1.
- Build metadata uses a plus sign: 1.0.0+build.1.

Simply adding an extra number like 1.2.3.4 isn’t a compliant way to indicate a pre-release or build label because it bypasses these standardized separators. This is more than just formatting; many SemVer-compatible tools require this structure to accurately interpret the version’s intent, so using 1.2.3.4 can disrupt tooling compatibility.

If you’re adding build-specific info, a proper SemVer example would be 1.2.3+4 or 1.2.3-4 rather than 1.2.3.4.

Therefore I recommend not using the word "SEM" or "SemVer" in this situation as it will confuse people.

Perhaps developers like @cdwmhcc @SelfRef @fuzzzerd @marlop352 can help out here with their interpretation of SemVer.

2024-11-05 15:42 UTC, cdwmhcc commented
> My preference is to use `kebab-case` (i.e. hyphen for delimiter) rather than mixing `-` and `_` for delimiters. That way, we can reserve underscore for use in things like `x86_64`.

My fault, it should be: `deskflow_1.17.0.0_macos_x86_64.dmg`

2024-11-05 16:41 UTC, teknowledgist commented
> Questions for Windows Packagers
> 1. windows or win ?
> 2. win$arch or win_$arch
> 3. How do you all prefer the arm one be labeled ?
> 4. MSI being windows only do we need to include windows or just the arch ? (i.e deskflow-v_x64.msi)

1. "win" is fine.
2. "win_$arch" please.
3. "arm64" is fine.
4. Please include "win" even though `.msi` is Windows-only.

If there will never be a 4-level version number, then please don't add the extra "0".  The download URL with two different kinds of versioning is driving me nuts (https://github.com/deskflow/deskflow/releases/download/v1.17.0/deskflow-1.17.0.0_win64.msi).

Please use underscores, `_`,  to separate data bits in the name (e.g. `deskflow_1.18.0_windows_x64.msi` in `$name_$version_$platform_$arch.$extension` format).  Hyphens, `-`, should be reserved for hyphenated names (e.g. `Deskflow-Pro`)

My $.02

2024-11-05 16:56 UTC, sithlord48 commented
I will use underscore but i will not do 
`deskflow_1.14.0` I will do only `deskflow-1.14.0` as this how most linux distros want the package name.. 
also having deskflow-verison_os makes it really easy to read the version you look for the - and read until the next _ .  need the os look for _ and read until the next _

2024-11-05 17:30 UTC, marlop352 commented
I would prefer `deskflow_type-version-os-arch`, the type being "pro" or something like that if it's ever needed.
For now it would be: `deskflow-version-os-arch`, having a `_` for the `x86_64` arch

2024-11-05 18:16 UTC, sithlord48 commented
the architecture part will come from cmake that is x86_64 , AMD64 , ARM64 and afew others depending on the OS and how it reports it  
for windows we are using x64 for `x86_64` all others oses are using `x86_64` in the new scheme. If you windows ppl want the windows one to say x86_64 too that is fine with me.

2024-11-05 18:27 UTC, teknowledgist commented
In Windows world, `x64` means 64-bit only.  Use `x86_64` only if it will work on either 32-bit or 64-bit systems.  Ideally, that means it has one installer with both builds, because 32-bit (i.e. `x86` or `win32`) should also work on 64-bit Windows.

2024-11-05 18:31 UTC, marlop352 commented
For me `x86_64` and `x64` are the same so I don't really care which of the two is used.

2024-11-05 18:33 UTC, marlop352 requested changes

2024-11-05 18:33 UTC, marlop352 commented on scripts/package.py
>      # Underscore is used to delimit different parts of the filename (e.g. version, OS, etc).
The comments should also be updated to reflect the new scheme.

2024-11-05 18:52 UTC, sithlord48 commented on scripts/package.py
>      # Underscore is used to delimit different parts of the filename (e.g. version, OS, etc).
good point i should remove this comment its kinda obvious what the next line does

2024-11-06 13:32 UTC, marlop352 approved these changes

2024-11-06 14:13 UTC, nbolton commented
> * Arch: `deskflow-continuous-arch-x86_64.pkg.tar.zst`
> * Debian: `deskflow-continuous-debian-trixie-x86_64.deb`
> * Fedora 40: `deskflow-continuous-fedora-40-x86_64.rpm`
> * Fedora 41: `deskflow-continuous-fedora-41-x86_64.rpm`
> * mac OS (arm): `deskflow-continuous-macos-arm64.dmg`
> * mac OS (64 bit): `deskflow-continuous-macos-x86_64.dmg`
> * Suse: `deskflow-continuous-opensuse-tumbleweed-x86_64.rpm`
> * Windows (x86_64) `deskflow-continuous-win-x64.msi`
> * Windows (arm) `deskflow-continuous-win-arm64.msi`

The PR description seems to have gone out of sync with the code.

2024-11-06 14:15 UTC, nbolton commented on .github/workflows/ci.yml
> +            mv *.pkg.tar.zst deskflow-${{env.DESKFLOW_PACKAGE_VERSION}}_${OSNAME}_${ARCH}.pkg.tar.zst
Are the underscores intentional?
https://github.com/deskflow/deskflow/pull/7845#issuecomment-2459866387

2024-11-06 14:19 UTC, sithlord48 commented on .github/workflows/ci.yml
> +            mv *.pkg.tar.zst deskflow-${{env.DESKFLOW_PACKAGE_VERSION}}_${OSNAME}_${ARCH}.pkg.tar.zst
no let me update that

2024-11-06 14:46 UTC, nbolton approved these changes

2024-11-06 16:32 UTC, merged