build: Add Nix Flake & derivation scaffolding
deskflow/deskflow pull request #7850
Opened 2024-11-02 16:50 UTC by shymega

build: Add Nix Flake & derivation scaffolding
Also added a CI workflow for the Flake and derivation checks. Will be
upstreaming the derivation to Nixpkgs, but only on Deskflow releases.

Having the Flake & derivation in this repo allows people to build from
Git, or enter a development environment.

You will see `/.envrc` - this is for `direnv`, and if people have Nix
installed, it will automatically generate a developer environment,
Nixified.

One big benefit is that people can simply run the command:

`nix run github:deskflow/deskflow` - and Nix will fetch the latest
commit, build, and run Deskflow in one hit.

Later on, we should add 'Cachix' support, which means binaries will be
built and hosted on a Nix cache. This is free of charge.

Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

2024-11-02 16:55 UTC, sithlord48 commented
can the supporting nix files be placed in res/dist/nix or somewhere other then the root of the project ?

2024-11-02 16:59 UTC, sithlord48 commented
also is it possible have this as part of our current build matrix and not its own workflow  ?

2024-11-02 17:45 UTC, shymega commented
> can the supporting nix files be placed in res/dist/nix or somewhere other then the root of the project ?

Only `deskflow.nix`. The rest have to be in the root - in particular `flake.*`.

2024-11-02 17:45 UTC, shymega commented
> also is it possible have this as part of our current build matrix and not its own workflow ?

Yes, but I think it should be under a separate job.

2024-11-02 18:02 UTC, sithlord48 requested changes
I am not a fan of any distro specific stuff being in the root of the repo.

2024-11-02 18:02 UTC, sithlord48 commented on .github/workflows/nix-tests.yml
> +---
Can we do this as a composite action and not a workflow

2024-11-02 18:04 UTC, shymega commented
> I am not a fan of any distro specific stuff being in the root of the repo.

`default.nix`, `shell.nix`, and `flake.*` *must* be in the root of the repo. One could argue we shouldn't have:

- `sonar-project.properties`
- `vcpkg-configuration.json`
- `vcpkg.json`
- `Chocolatey.config`

Chocolately, for example is Windows-specific.

2024-11-02 18:05 UTC, shymega commented on .github/workflows/nix-tests.yml
> +---
I don't think a composite action is worth it for two, 3-4 steps workflows. Let's keep it simple.

2024-11-02 18:08 UTC, sithlord48 commented
> > I am not a fan of any distro specific stuff being in the root of the repo.
> 
> `default.nix`, `shell.nix`, and `flake.*` _must_ be in the root of the repo. One could argue we shouldn't have:
> 
>     * `sonar-project.properties`
> 
>     * `vcpkg-configuration.json`
> 
>     * `vcpkg.json`
> 
>     * `Chocolatey.config`
> 
> 
> Chocolately, for example is Windows-specific.

 -  vcpkg works for everything  you can get all the depends thru it on any os..
 -  i have a commit to remove the chocolately stuff as we don't even use it (and the Brewfile as well) 
 -  Sonar is code scanning and we do this so every build can be better  and i would prefer to also not have that in root but its also one file not 4.

2024-11-02 18:10 UTC, sithlord48 commented on .github/workflows/nix-tests.yml
> +---
Thats pretty normal in this repo

2024-11-02 18:11 UTC, shymega commented
> > > I am not a fan of any distro specific stuff being in the root of the repo.
> > 
> > 
> > `default.nix`, `shell.nix`, and `flake.*` _must_ be in the root of the repo. One could argue we shouldn't have:
> > ```
> > * `sonar-project.properties`
> > 
> > * `vcpkg-configuration.json`
> > 
> > * `vcpkg.json`
> > 
> > * `Chocolatey.config`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Chocolately, for example is Windows-specific.
> 
>     * vcpkg works for everything  you can get all the depends thru it on any os..
> 
>     * i have a commit to remove the chocolately stuff as we don't even use it (and the Brewfile as well)
> 
>     * Sonar is code scanning and we do this so every build can be better  and i would prefer to also not have that in root but its also one file not 4.

OK. Well, I can't change how Nix works, but for this case, I can move `deskflow.nix` to a subdirectory - but not the rest. It's just the way Nix 'discovers' each repo.

I would like to see what @nbolton thinks.

2024-11-02 18:12 UTC, shymega commented on .github/workflows/nix-tests.yml
> +---
It sounds overkill to me. For workflows like building for Linux, or Windows - yes. But this is such a small set of jobs, it's just not worth it IMO.

2024-11-02 18:21 UTC, sithlord48 commented on .github/workflows/nix-tests.yml
> +---
We had the author for winget packaging also make their few step workflow into an action.

2024-11-02 18:37 UTC, sithlord48 commented
> > > > I am not a fan of any distro specific stuff being in the root of the repo.
> > > 
> > > 
> > > `default.nix`, `shell.nix`, and `flake.*` _must_ be in the root of the repo. One could argue we shouldn't have:
> > > ```
> > > * `sonar-project.properties`
> > > 
> > > * `vcpkg-configuration.json`
> > > 
> > > * `vcpkg.json`
> > > 
> > > * `Chocolatey.config`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Chocolately, for example is Windows-specific.
> > 
> > 
> > ```
> > * vcpkg works for everything  you can get all the depends thru it on any os..
> > 
> > * i have a commit to remove the chocolately stuff as we don't even use it (and the Brewfile as well)
> > 
> > * Sonar is code scanning and we do this so every build can be better  and i would prefer to also not have that in root but its also one file not 4.
> > ```
> 
> OK. Well, I can't change how Nix works, but for this case, I can move `deskflow.nix` to a subdirectory - but not the rest. It's just the way Nix 'discovers' each repo.
> 
> I would like to see what @nbolton thinks.

Is it possible to have the flake stuff in another repo and have it pull this one as part of its build ?
i.e nix users pull `deskflow/nix-flake`  that repo only contains the nix build stuff

2024-11-02 18:47 UTC, shymega commented
> > > > > I am not a fan of any distro specific stuff being in the root of the repo.
> > > > 
> > > > 
> > > > `default.nix`, `shell.nix`, and `flake.*` _must_ be in the root of the repo. One could argue we shouldn't have:
> > > > ```
> > > > * `sonar-project.properties`
> > > > 
> > > > * `vcpkg-configuration.json`
> > > > 
> > > > * `vcpkg.json`
> > > > 
> > > > * `Chocolatey.config`
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Chocolately, for example is Windows-specific.
> > > 
> > > 
> > > ```
> > > * vcpkg works for everything  you can get all the depends thru it on any os..
> > > 
> > > * i have a commit to remove the chocolately stuff as we don't even use it (and the Brewfile as well)
> > > 
> > > * Sonar is code scanning and we do this so every build can be better  and i would prefer to also not have that in root but its also one file not 4.
> > > ```
> > 
> > 
> > OK. Well, I can't change how Nix works, but for this case, I can move `deskflow.nix` to a subdirectory - but not the rest. It's just the way Nix 'discovers' each repo.
> > I would like to see what @nbolton thinks.
> 
> Is it possible to have the flake stuff in another repo and have it pull this one as part of its build ? i.e nix users pull `deskflow/nix` that repo only contains the nix build stuff

No, it's not. I really don't think it's a big issue - plenty of repos have Nix stuff in their root.

2024-11-02 18:47 UTC, shymega commented on .github/workflows/nix-tests.yml
> +---
I've never used composite actions, so I don't know.

2024-11-02 19:12 UTC, sithlord48 commented on .github/workflows/nix-tests.yml
> +---
its pretty simple check out our actions folder just be sure to add a shell for any run commands.

2024-11-02 19:17 UTC, sithlord48 commented
according to this https://discourse.nixos.org/t/flake-nix-in-root-of-git-or-deeper/27859 

you can put the files anywhere and just use the command `github:deskflow/deskflow?dir=dist/nix`

2024-11-02 19:19 UTC, shymega commented
Right, but that's not user-friendly - users shouldn't have to pass a query string.

I'm going to try a symlink approach. One sec.

2024-11-05 13:34 UTC, nbolton commented
Let's take a vote: #7858

2024-11-08 20:11 UTC, closed without merging

2024-11-08 20:11 UTC, shymega commented
No longer going to be active in this project for the foreseeable future. Closing.

2024-11-12 14:15 UTC, nbolton commented
Sorry to hear that, @shymega. You're welcome back any time and I hope that we can change the thing that made you feel this way.

2024-11-13 09:00 UTC, shymega commented
I should have stepped back, and recognised I was finding the discussion
difficult.

I am happy to reopen this PR - I have been given some thought to the Nix
side of things.

It is important to remember that this PR is not merely a packaging
effort. It is, in fact, also a development environment. For example, if
one had Nix and `direnv` installed, when they `cd` into the Deskflow
repository, a developer environment is automatically set up and entered.
With `devenv`, another Nix tool, a VS Code devcontainer can also be
generated. `devenv` would be limited to the Nix Flake.

 From my POV, I think this PR is not limited in scope to packaging. That
is just one of its features.

With regards to passing `?dir` to the Flake, this would be very
unergonomic. Nearly all repositorires, IIRC, do not do it this way. It
would make Deskflow the minority, which might present a bad image to the
project.

With regards to build dependencies, the Nix side of things would only be
activated if the user has Nix and `direnv` installed. I think, however,
it would be good to add a CI workflow for Nix, and also to move the
`deskflow.nix` file (derivation) to a separate folder. The
`default.nix`/`shell.nix` are required for the legacy Nix tooling, which
is still in use. They act as shims. They, and `flake.{lock,nix}` must be
kept in the root of the repository.

I hope this makes thinsgs more clear.

On 12.11.2024 06:16, Nick Bolton wrote:
>Sorry to hear that, @shymega. You're welcome back any time and I hope that we can change the thing that made you feel this way.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/deskflow/deskflow/pull/7850#issuecomment-2470653289
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
Best wishes,
--
Dom Rodriguez

2024-11-13 12:30 UTC, sithlord48 commented
If you can't do it without putting them not in the root can you make a a repo like deskflow/nix to contain the nix needed parts.

2024-11-14 08:30 UTC, shymega commented
On 13.11.2024 04:31, Chris Rizzitello wrote:
>If you can't do it without putting them not in the root can you make a a repo like deskflow/nix to contain the nix needed parts.

No, and that would, as I illustrated before, would be unergonomic. You
would still need a way to 'link' the two together - i.e, `deskflow/nix`,
and `deskflow/deskflow`. This is not a good solution, and would confuse
people.

As I said before, the best solution is to have the Nix files in the root
of the Deskflow repository. This is not a mere packaging effort - it
also acts as a one-click developer environment, including with
`devcontainers`.

cc: @nbolton - keen for your thoughts here.

Best wishes,
--
Dom Rodriguez

2024-11-14 13:04 UTC, nbolton commented
I haven't voted on #7858 yet, as I don't want to skew the results given that we have so few voters right now as our community is bootstrapping.

Small sample size but it is split 50/50 so far...

![image](https://github.com/user-attachments/assets/8c800fb8-a32b-45e1-a413-b33f68cb2756)

I think it all comes down to the vote. What other developers want to see Nix config files in the root?

My take: A separate repo could add complexity and confusion.

2024-11-15 00:59 UTC, sithlord48 commented
Why not make a package on [nixpkgs](https://github.com/nixos/nixpkgs) that seams like the logical place since that is the default nix "repo"

2024-11-15 07:45 UTC, shymega commented
On 14.11.2024 17:00, Chris Rizzitello wrote:
>Why not make a package on [nixpkgs](https://github.com/nixos/nixpkgs) that seams like the logical place since that is the default nix "repo"

That's only one part of the puzzle.

Most, if not all Nix-enabled projects do both - a package in upstream
Nixpkgs, and a Flake in the downstream repo. [This][atuin] might be a
good example of what I'm talking about.

I think we're going round in circles here - the original point of this
PR was for a Nix Flake for Deskflow (downstream), which is not a pure
packaging effort, but also a developer environment.

[atuin]: https://github.com/atuinsh/atuin

Best wishes,
--
Dom Rodriguez

2024-11-15 07:45 UTC, shymega commented
On 14.11.2024 05:05, Nick Bolton wrote:
>I haven't voted on #7858 yet, as I don't want to skew the results given that we have so few voters right now as our community is bootstrapping.

Understandable.

>Small sample size but it is split 50/50 so far...
>
>![image](https://github.com/user-attachments/assets/8c800fb8-a32b-45e1-a413-b33f68cb2756)
>
>I think it all comes down to the vote. What other developers want to see Nix config files in the root?

It's not just config files, but a way to develop Deskflow on NixOS, and
as a one-click developer environment.

For me, this would be necessary for me to work on Deskflow. NixOS does
not use a FHS hierarchy, which Deskflow expects.

>My take: A separate repo could add complexity and confusion.

Agreed, and it's also very messy to do so. I think we need to be clear
on the fact that my PR is not a packaging effort first and foremost.
Let's try and keep an open mind, and think with a wider range on the
practical applications.

Best wishes,
--
Dom Rodriguez

2024-11-15 12:43 UTC, sithlord48 commented
Its packaging, and it seams that someone has already added it to NIX 

If you need them locally then put the in your local checked out code.

2025-06-21 22:40 UTC, shymega commented
I've adjusted the PR and it works with the upstream Nixpkgs repo as the source derivation.

The premise now is that the Flake overrides the `src` attribute in Nixpkgs for Deskflow to use _this repo_, which allows for a development environment and a one-click command to build directly from Git. Nixpkgs cannot do this.

I will open a new PR tomorrow - although I have pushed to this branch. I would like to revisit; the conclusion misses the point of the PR.