Build Wix with Cpack
deskflow/deskflow pull request #7915
Opened 2024-11-22 07:42 UTC by sithlord48

Based on #7914 <- must land first

 - Build a wix package with cpack 
 - Remove the old wix creation and clean up where possible

Wix installer needs to be check several changes 
- Does not deploy openssl.exe 
  - was not able to cause an issue when testing without it
  - There could be code to clean up if its truly unused
- Does not set additional regkeys the old wix item set. 
 - Some we don't need (the hires ones should be work via the manifest)
 - Users should be prompted to allow deskflow access thru the fire wall 
 - Perhaps some releated to setting up the service.

2024-12-03 17:13 UTC, nbolton requested changes
The banner text color has changed from white to black. Can this be changed to white using CPack?

![deskflow text color](https://github.com/user-attachments/assets/b4c81fd5-762e-4bc2-b9d4-ebc6030a03d8)

2024-12-03 17:13 UTC, nbolton requested changes
The app name is lower case. Can it be changed to title case?
`deskflow` -> `Deskflow`
![deskflow lower case](https://github.com/user-attachments/assets/318c4b69-2048-4b2e-9837-bc82c0a94c49)

2024-12-03 17:16 UTC, nbolton requested changes
The app no longer auto-starts as it did before. 

Auto start is fairly standard with Windows apps since the start menu is a bit of a pain on Windows. Alternatively, creating a desktop shortcut is usually the next best thing (for the same reason). 

Windows is the only OS we tend to do this on, due to its usability limitations.

2024-12-03 17:18 UTC, nbolton requested changes

2024-12-03 17:18 UTC, nbolton commented on deploy/dist/wix/Product.wxs
> -			<Merge Id="VC_Redist" SourceFile="$(var.DeployResDir)\dist\wix\msm\Microsoft_VC142_CRT_x64.msm" DiskId="1" Language="0"/>
Removing this causes:
![windows missing dep](https://github.com/user-attachments/assets/6b6c810b-8185-4ac4-ba2d-cf13d05b0a53)

2024-12-03 17:25 UTC, nbolton requested changes
Can we change the license text size? It's pretty hard to read.

![win11 text size](https://github.com/user-attachments/assets/82754581-7a54-4466-9084-e21c973424b7)

2024-12-03 18:19 UTC, sithlord48 commented on .github/workflows/continuous-integration.yml
> +#          signtool sign -f ${{ secrets.WINDOWS_PFX }}  -p '${{ secrets.WINDOWS_PFX_PASS }}' -t http://timestamp.digicert.com -fd SHA256 ${{github.workspace}}/build/deskflow-*.msi
sure i just didn't want to forget it , this way all we need todo is remove the comments when we our repo is setup

2024-12-03 18:39 UTC, sithlord48 commented on .github/actions/install-dependencies/action.yml
> +        wix extension add --global WixToolset.Firewall.wixext/5.0.2
Done (added to wiki) these are already used

2024-12-03 23:59 UTC, sithlord48 commented on deploy/dist/wix/Product.wxs
> -			<Merge Id="VC_Redist" SourceFile="$(var.DeployResDir)\dist\wix\msm\Microsoft_VC142_CRT_x64.msm" DiskId="1" Language="0"/>
Should be resolved now, Tested latest installer in a clean win10 VM and it runs after installing.

2024-12-04 00:01 UTC, sithlord48 commented
> The app no longer auto-starts as it did before.
> 
> Auto start is fairly standard with Windows apps since the start menu is a bit of a pain on Windows. Alternatively, creating a desktop shortcut is usually the next best thing (for the same reason).
> 
> Windows is the only OS we tend to do this on, due to its usability limitations.

This is  due to the missing dlls , should work now

2024-12-04 11:59 UTC, nbolton commented on .github/workflows/continuous-integration.yml
> +#          signtool sign -f ${{ secrets.WINDOWS_PFX }}  -p '${{ secrets.WINDOWS_PFX_PASS }}' -t http://timestamp.digicert.com -fd SHA256 ${{github.workspace}}/build/deskflow-*.msi
If it was a new draft PR, I think it'd be less likely to be forgotten.

2024-12-04 12:16 UTC, nbolton requested changes
Maybe I missed this on the last pass. The path shouldn't have the version number in it.

![df win11 path](https://github.com/user-attachments/assets/cdb5d161-821b-44de-ad08-0397419ccda3)

2024-12-04 12:19 UTC, nbolton requested changes
Hmm, start menu item seems to be missing.

![deskflow missing start](https://github.com/user-attachments/assets/3b05f60e-a673-439a-9799-9886dafa2c4e)
![deskflow start menu dir](https://github.com/user-attachments/assets/ef2337b4-1a8c-43a2-963a-a81bab79d78d)

2024-12-04 12:21 UTC, nbolton requested changes
Seeing an OpenSSL dir error.

![deskflow openssl missing](https://github.com/user-attachments/assets/1a48583c-9e8d-4f57-9989-0828fbb0a4bc)

2024-12-06 12:48 UTC, nbolton reviewed
Looks like your firewall exception is not working as intended. The rule added by the MSI has a weird filename.

![firewall exception](https://github.com/user-attachments/assets/ef56a4c6-9668-4667-9dd6-69d50f381978)

![firewall rules](https://github.com/user-attachments/assets/5f2084fb-73a5-4bd9-94d5-8ca491510d79)

2024-12-18 17:10 UTC, nbolton approved these changes
Tested on fresh Windows 11 VM, works great. 

7th time's a charm :wink:

2024-12-18 17:10 UTC, merged