Peerbase
deskflow/deskflow pull request #7931
Opened 2024-11-28 13:26 UTC by sithlord48

- There are several changes for SSL peer checking This pr adds most of the supporting changes from barrier.

2025-01-20 11:03 UTC, nbolton commented
I removed myself as reviewer while this is draft. Let me know if you actually need me to review.

2025-02-12 16:46 UTC, nbolton commented
Oh, its finally ready! Will try to review tomorrow.

2025-02-14 10:11 UTC, nbolton commented
I am concerned that this will confuse users. Why would they need to click this button? 
![image](https://github.com/user-attachments/assets/4dd3c105-9184-4be8-9a22-eb6df47bca68)

It's likely in my experience that they will click it and think, "Hey those don't match" to which we will respond "Of course they don't match, they're not supposed to"... and we'll repeat that response until ultimately we remove the button as we tire of this discussion.

TL;DR: People don't read things and will end up wasting our time with questions that don't make sense.

2025-02-14 13:42 UTC, nbolton commented
> With the dialog up there is no way to see your local keys to confirm what is on the screen in the case a new server connecting to a new client both will have the dialog up showing the others keys with no way to view their own. I do not want to add the local keys into dialog as having to see them to compare can happen in cases where you are not needing to see the local ones for example a known client or sever generates new keys.

Which problem are we trying to solve?
1. In case of a MITM, the user will see this dialog abruptly, and because they can't see what their existing client-side fingerprint was (to compare with the server) they may be tricked into thinking that the fingerprint hasn't changed.
2. When the client connects and you see the dialog on the server, you cannot check your local fingerprints to ensure that the fingerprint on the client side is valid.

In both cases, I see the value of the button but I still think the wording will confuse some people.

I also think that the word "this" will cause confusion: Does "this computer" mean the client that is connecting or this current computer that I'm on? To us devs, it's obviously this current computer that I'm on but that's because we know how it works.

2025-02-14 13:49 UTC, sithlord48 commented
> > With the dialog up there is no way to see your local keys to confirm what is on the screen in the case a new server connecting to a new client both will have the dialog up showing the others keys with no way to view their own. I do not want to add the local keys into dialog as having to see them to compare can happen in cases where you are not needing to see the local ones for example a known client or sever generates new keys.
> 
> Which problem are we trying to solve?
> 
>     1. In case of a MITM, the user will see this dialog abruptly, and because they can't see what their existing client-side fingerprint was (to compare with the server) they may be tricked into thinking that the fingerprint hasn't changed.
> 
>     2. When the client connects and you see the dialog on the server, you cannot check your local fingerprints to ensure that the fingerprint on the client side is valid.
> 
> 
> In both cases, I see the value of the button but I still think the wording will confuse some people.
> 
> I also think that the word "this" will cause confusion: Does "this computer" mean the client that is connecting or this current computer that I'm on? To us devs, it's obviously this current computer that I'm on but that's because we know how it works.

Yes lets word it better

2025-02-14 13:51 UTC, nbolton commented
Hmm, problem. Simple setup with 2 computers. I cleared my settings on both computers. On the server, I see no way to see the local server's fingerprint.
![image](https://github.com/user-attachments/assets/7a1fa8fa-a91f-4582-b0b6-dcc820d25bbd)

The only dialog I see is on the client:
TODO

2025-02-14 13:55 UTC, sithlord48 commented
Setting clearing really needs to restart the Gui , i would consider that a seperate issue

2025-02-17 12:36 UTC, nbolton requested changes
Works well. Nits aside, I'm concerned about a couple of things.

2025-02-17 12:36 UTC, nbolton commented on src/lib/gui/config/AppConfig.h
> +  bool m_RequireClientCert = false;
Less secure by default is less secure. Would defaulting the 'require client certs' setting to `true` make sense? I fear with this disabled, 95% of users won't ever turn it on.

```suggestion
  bool m_RequireClientCert = true;
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/gui/core/ServerConnection.cpp
> +      m_pDeps->showNewClientPrompt(m_pParent, clientName, m_appConfig.tlsEnabled() && m_appConfig.requireClientCerts());
Does it make sense to call the 3rd bool arg `previouslyAccepted`? 
Wouldn't something like `requireClientCerts` make sense?

```suggestion
  const auto result =
      m_pDeps->showNewClientPrompt(m_pParent, clientName, m_appConfig.tlsEnabled() && m_appConfig.requireClientCerts());
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/gui/messages.cpp
> +    const QPushButton *add = message.addButton("Add client", QMessageBox::AcceptRole);
For consistency.
```suggestion
    const QPushButton *add = message.addButton("New Client", QMessageBox::AcceptRole);
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/gui/messages.cpp
> +        QString("A new client \"%1\" has been accepted you must add it to your servers screen layout").arg(clientName)
Improved grammar.
```suggestion
        QString("A new client called '%1' has been accepted. You'll need to add it to your server's screen layout.").arg(clientName)
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/gui/messages.cpp
> +NewClientPromptResult showNewClientPrompt(QWidget *parent, const QString &clientName, bool previouslyAccepted)
Why do we not allow users to ignore clients when 'require client certs' is on?

Also the UI wording is now very different between the two logic branches. If we really do need the logic branch, perhaps some de-duping is needed.

2025-02-17 12:36 UTC, nbolton commented on src/lib/net/SecureListenSocket.h
> +  SecurityLevel m_securityLevel;
As this is only set in ctor, const makes sense rather than it being mutable.
```suggestion
  const SecurityLevel m_securityLevel;
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/net/SecureSocket.cpp
> +static int cert_verify_ignore_callback(X509_STORE_CTX *, void *)
Free functions are normally defined separately--form the class functions--at the top of the source file.

Also it should be `camelCase`.

```suggestion
static int verifyIgnoreCertCallback(X509_STORE_CTX *, void *)
```

2025-02-17 12:36 UTC, nbolton commented on src/lib/net/SecureSocket.cpp
> +    // FIXME: this is fatal
I wouldn't call this fatal. Normally "fatal" means the application must exit.

2025-02-17 12:36 UTC, nbolton commented on src/lib/net/SecurityLevel.h
> +  PeerAuth   /** The connection is encrypted and the peer has been authenticated */
Do these comments really add much?

2025-02-17 13:00 UTC, sithlord48 commented on src/lib/net/SecureSocket.cpp
> +    // FIXME: this is fatal
the comment is from the ported code so i left is as is.

2025-02-17 13:02 UTC, sithlord48 commented on src/lib/net/SecurityLevel.h
> +  PeerAuth   /** The connection is encrypted and the peer has been authenticated */
Yes these are doxygen comments and will create a table tell you about the enum the generated table will look something like [this](https://sithlord48.github.io/ff7tk/classFF7SaveInfo.html#a26b833c52018990f2bd00a27bed3b958)

2025-02-17 13:04 UTC, sithlord48 commented on src/lib/gui/core/ServerConnection.cpp
> +      m_pDeps->showNewClientPrompt(m_pParent, clientName, m_appConfig.tlsEnabled() && m_appConfig.requireClientCerts());
Nope when we call this if we have peer auth or encryption then the use has all ready accepted that they want the client to be able to connect.  so `previouslyAccepted` is what that represents.

2025-02-17 13:06 UTC, sithlord48 commented on src/lib/gui/messages.cpp
> +NewClientPromptResult showNewClientPrompt(QWidget *parent, const QString &clientName, bool previouslyAccepted)
We don't . When its on we show a slightly different box that just says you have to add this to the screen layout.

2025-02-17 13:26 UTC, sithlord48 commented on src/lib/gui/messages.cpp
> +    const QPushButton *add = message.addButton("Add client", QMessageBox::AcceptRole);
With in the context of the that wording is sane
```
      A New client 'foo' want to connect
                         [Add client] [Ignore]
```

Vs. 

```
      A New client 'foo' want to connect
                         [New client] [Ignore]
```
 
If i was gonna change the previous text (as it been in the dialog forever) 
I would use the standard action names
```
      A New client 'foo' want to connect
                                      [Accept] [Reject]
```

2025-02-17 13:45 UTC, sithlord48 commented on src/lib/gui/messages.cpp
> +NewClientPromptResult showNewClientPrompt(QWidget *parent, const QString &clientName, bool previouslyAccepted)
> Why do we not allow users to ignore clients when 'require client certs' is on? I.e. there is no 'Ignore' button on this logic branch. Also, the UI wording is now different between the two logic branches. Should it be?

Good question, When peer auth is on the user has already accepted the client connection in the dialog where they view the remote keys. This dialog will show after that one. This is why that version is only an information box to tell the user that they need to add the client before they are taken to the sever config page. I added it cause it was a bit weird to just be thrown into the screen config .

2025-02-17 15:42 UTC, nbolton commented on src/lib/gui/core/ServerConnection.cpp
> +      m_pDeps->showNewClientPrompt(m_pParent, clientName, m_appConfig.tlsEnabled() && m_appConfig.requireClientCerts());
I don't see how this makes sense. How can `requireClientCerts` returning true prove that a client has been previously accepted? All it proves is that you checked the 'Require client certificates' checkbox.

2025-02-17 15:44 UTC, nbolton commented on src/lib/gui/messages.cpp
> +    const QPushButton *add = message.addButton("Add client", QMessageBox::AcceptRole);
I can't see how the code in its current state makes sense. In both cases, you should add it to the layout if you want the client to connect. Why would one give you the opportunity to ignore and not the other. And why would the variable be called `previouslyAccepted` when it's related to a new client?

This is all seriously confusing code.

2025-02-17 16:18 UTC, nbolton commented on src/lib/gui/messages.cpp
> +    const QPushButton *add = message.addButton("Add client", QMessageBox::AcceptRole);
Not for future self: After having a quick call, this all makes way more sense now :tada:

2025-02-17 16:22 UTC, nbolton approved these changes

2025-02-17 16:26 UTC, merged

2025-02-18 11:19 UTC, nbolton commented
/tip $100 @sithlord48

2025-03-28 11:19 UTC, nbolton commented
@sithlord48 The milestone set for this PR (2.0.0) may be causing some confusion. We should review what issues/PRs are in 2.0.0 milestone.

2025-03-28 11:56 UTC, sithlord48 commented
This is a goal we need to completed before 2.0.0 can be released.. We don't hold code back for a specific release we just land it when ready and our milestones act  as a guide for us  to know when we can say we can bump to version ...