fix: `qDebug` doesn't work on Fedora
deskflow/deskflow pull request #7977
Opened 2024-12-16 15:52 UTC by nbolton

2024-12-16 16:25 UTC, nbolton commented on src/gui/src/main.cpp
> +  qputenv("QT_LOGGING_RULES", "*.debug=true;qt.*=false");
Alternative: `QLoggingCategory::setFilterRules(QStringLiteral("driver.usb.debug=true"));`

2024-12-16 16:59 UTC, sithlord48 commented on src/gui/src/main.cpp
> +  qputenv("QT_LOGGING_RULES", "*.debug=true;qt.*=false");
This rule could be for any OS but i would guard it on it being a debug build

2024-12-20 16:09 UTC, sithlord48 commented
Updated it please test.

2024-12-20 16:09 UTC, sithlord48 approved these changes
This way works for me

2024-12-26 13:46 UTC, sithlord48 submitted a review, later dismissed
LGTM

2024-12-26 16:05 UTC, nbolton commented
> Updated it please test.

Did not work, restored original hack.

2024-12-26 16:27 UTC, sithlord48 requested changes

2024-12-26 16:27 UTC, sithlord48 commented on src/apps/deskflow-gui/main.cpp
> +#if defined(Q_OS_UNIX)
Please only change for debug builds and also include the item only for these builds as well

2024-12-26 16:33 UTC, sithlord48 approved these changes

2024-12-26 16:48 UTC, merged