feat: Visiblity toggle for the log on the main window
deskflow/deskflow pull request #7994
Opened 2024-12-20 02:54 UTC by sithlord48

Add the ability to toggle the log 

When Deskflow opens, The log is collapsed and the widows size is fixed: 
![Screenshot_20241219_214321](https://github.com/user-attachments/assets/a22e1590-936b-4823-b193-0753ee834749)

If you expand the log: you can resize how you like and this size is remembered if you close the log it goes back to the above state. 
![Screenshot_20241219_214454](https://github.com/user-attachments/assets/a87bf809-8e73-4b05-81fb-123bd2bffb67)

2024-12-22 13:37 UTC, nbolton commented
> ![Screenshot_20241219_214321](https://private-user-images.githubusercontent.com/7450820/397597304-a22e1590-936b-4823-b193-0753ee834749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzQ4MzcsIm5iZiI6MTczNDg3NDUzNywicGF0aCI6Ii83NDUwODIwLzM5NzU5NzMwNC1hMjJlMTU5MC05MzZiLTQ4MjMtYjE5My0wNzUzZWU4MzQ3NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTMzNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YThlNmJmZDVjMDVjZTM1YjkwMmM4NGM4NTYxNzg5MjE3MzNlMjMxYjE5ZGM3ZTUwMDAyMTlkYWY2OWRlYjdiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BPAZazjn5l2v9bkPYhJK5vPY6LALHK40WNlyS8w9PYY)

Cool. I think it'd look neater if the server and client groupboxes were equally sized (50%+50%). Right now the left box is a bit smaller and it looks unintentional.

2024-12-22 13:38 UTC, nbolton requested changes
> ![Screenshot_20241219_214321](https://private-user-images.githubusercontent.com/7450820/397597304-a22e1590-936b-4823-b193-0753ee834749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzQ4MzcsIm5iZiI6MTczNDg3NDUzNywicGF0aCI6Ii83NDUwODIwLzM5NzU5NzMwNC1hMjJlMTU5MC05MzZiLTQ4MjMtYjE5My0wNzUzZWU4MzQ3NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTMzNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YThlNmJmZDVjMDVjZTM1YjkwMmM4NGM4NTYxNzg5MjE3MzNlMjMxYjE5ZGM3ZTUwMDAyMTlkYWY2OWRlYjdiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BPAZazjn5l2v9bkPYhJK5vPY6LALHK40WNlyS8w9PYY)

Cool. I think it'd look neater if the server and client groupboxes were equally sized (50%+50%). Right now the left box is a bit smaller and it looks unintentional.

2024-12-22 14:01 UTC, sithlord48 commented
The boxes are sized based on their contents that is how layouts work , I am not going to do anything to change that .

2024-12-26 14:06 UTC, nbolton reviewed
Up to you if you want to change.

2024-12-26 14:06 UTC, nbolton commented on src/apps/deskflow-gui/MainWindow.cpp
> +    setGeometry(x(), y() + 28, m_logRect.width(), m_logRect.height());
For readability, other developers would find it helpful for the magic number to be a constant. This is optimized out by the compiler so it won't add a perf overhead.

```suggestion
    // On macOS, the titlebar is part of the height so we need to adjust our Y coord to not "jump" up
    const auto kTitlebarOffset = 28;
    
    setGeometry(x(), y() + kTitlebarOffset, m_logRect.width(), m_logRect.height());
```

2024-12-26 14:06 UTC, nbolton commented on src/apps/deskflow-gui/MainWindow.cpp
> +  QTimer::singleShot(10, this, &MainWindow::updateSize);
Why 10?

2024-12-26 14:07 UTC, sithlord48 commented on src/apps/deskflow-gui/MainWindow.cpp
> +  QTimer::singleShot(10, this, &MainWindow::updateSize);
we just need a few ms for the events to be processed.  10 is the mininum

2024-12-26 14:07 UTC, sithlord48 commented on src/apps/deskflow-gui/MainWindow.cpp
> +    setGeometry(x(), y() + 28, m_logRect.width(), m_logRect.height());
that is fine i was just trying to avoid making a var that was not gonna be used too often

2024-12-26 14:11 UTC, nbolton commented on src/apps/deskflow-gui/MainWindow.cpp
> +    setGeometry(x(), y() + 28, m_logRect.width(), m_logRect.height());
Yeah I know what you mean.

2024-12-26 14:42 UTC, nbolton approved these changes

2024-12-26 14:42 UTC, nbolton commented on src/apps/deskflow-gui/MainWindow.cpp
> +#endif
Nice, yeah that makes sense to have the const in the ifdef, as it makes crystal clear what is different for macOS.

2024-12-26 14:45 UTC, nbolton approved these changes

2024-12-26 14:45 UTC, merged